name: Android Release Pipeline

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Set up JDK
        uses: actions/setup-java@v5
        with:
          distribution: temurin
          java-version: 17

      - name: Grant execute permission for Gradle
        run: chmod +x ./gradlew

      - name: Build, Scan, Sign & Release
        id: android
        uses: FreetimeMaker/android-build-sign-release@v1
        with:
          keystore: ${{ secrets.KEYSTORE_BASE64 }}
          keystore_password: ${{ secrets.KEYSTORE_PASSWORD }}
          key_alias: ${{ secrets.KEY_ALIAS }}
          key_password: ${{ secrets.KEY_PASSWORD }}
          gradle_task: assembleRelease
          scan: false

      - name: Upload signed APK
        uses: actions/upload-artifact@v7
        with:
          name: Signed APK
          path: ${{ steps.android.outputs.signed_apk }}

      # Optional: Create GitHub Release
      - name: Create Release
        if: startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v3
        with:
          files: ${{ steps.android.outputs.signed_apk }}
